export function createInitialState() {
  return {
    screen: "home",
    answers: {},
    config: null,
    route: [],
    preparedRuns: {},
    todayStatus: "normal",
    worldSeed: 1,
    worldLayout: null,
    worldObstacles: null,
    playerStyle: "male",
    playerName: "",
    delivered: [],
    player: { x: -4320, y: -3240, facing: 1, headingX: 1, headingY: 0, headingAngle: 0 },
    keys: new Set(),
    touchThrottle: 0,
    touchSteer: 0,
    autoForward: false,
    autoNavPath: null,
    autoNavTargetId: null,
    autoNavIndex: 0,
    autoNavWaypoint: null,
    autoNavMoving: false,
    autoAvoiding: false,
    autoAvoidTimer: 0,
    autoAvoidCooldown: 0,
    autoStuckTime: 0,
    autoNavWaitUntil: 0,
    easyMode: false,
    highContrast: false,
    familyMessage: "",
    gratitudeCards: [],
    memoryPrompt: null,
    isPlaying: false,
    isPaused: false,
    message: "阿铃：今天见到你真高兴。",
    lastTime: performance.now(),
    floatTime: 0,
    delivery: null,
    comic: null,
    houseReaction: null,
    lastNavHintAt: -99,
    nextThoughtAt: 12,
    lastThoughtDeliveryIndex: -1,
    summaryEarly: false,
    lastSafetyHintAt: -99,
    lastRestHintAt: -99,
    nearTraffic: null,
    trafficObstacles: [],
    trafficBump: null,
    lastTrafficBumpAt: -99,
  };
}

export function currentTarget(state) {
  return state.route[state.delivered.length];
}
